- name: Start rsyslog
  service: name=rsyslog state=started enabled=true

- name: Reload rsyslog
  service: name=rsyslog state=reloaded

- name: Restart rsyslog
  service: name=rsyslog state=restarted
